version: "{build}"

skip_tags: true

environment:
  matrix:
    - nodejs_version: "5.0"

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

build: off

platform:
  - x64

test_script:
  - node --version
  - npm --version
  - npm run lint && npm run test